# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-VisualBrowser
version:      0.13
version_from: lib/Tk/VisualBrowser.pm
installdirs:  site
requires:
    Tk::XPMs:                      1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
